#!/bin/bash

workdir=/home/coreyschultz/1.Projects/2.Sorghum.Resistance.Project/1.Sorghum.Data/Sorghum_PuerRico_Data_B
cd $workdir
database=$workdir/Sobi2300DB 
contigs=$workdir/Sobic05G172300contigB.fa
consens=$workdir/Sobic05G172300consB.fa

echo Good Job Corey!

##turn my consensus sequence into a databast to blast agaisnt
#makeblastdb -in $consens -dbtype nucl -out $workdir/Sobi2300DB 

##blast my contigs file against the consensus database
for F in /home/coreyschultz/1.Projects/2.Sorghum.Resistance.Project/1.Sorghum.Data/Sorghum_PuerRico_Data_B/Sobic05G172300contigsB/*.TXT
do
	blastn -db $database -query $F -num_threads 4 -out ${F%.*}.txt
done

echo Blast Complete!

for F in /home/coreyschultz/1.Projects/2.Sorghum.Resistance.Project/1.Sorghum.Data/Sorghum_PuerRico_Data_B/Sobic05G172300contigsB/*.txt
do
	mv $F $workdir/2300SNPs
done
